//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float4 GammaColorScaleAndInverse;
//   float4 GammaOverlayColor;
//   float LUTWeights[5];
//   float4 SceneColorize;
//   float4 SceneInverseHighLights;
//   float4 SceneMidTones;
//   float4 SceneScaledLuminanceWeights;
//   float4 SceneShadowsAndDesaturation;
//   sampler2D Texture1;
//   sampler2D Texture2;
//   sampler2D Texture3;
//   sampler2D Texture4;
//
//
// Registers:
//
//   Name                        Reg   Size
//   --------------------------- ----- ----
//   SceneShadowsAndDesaturation c0       1
//   LUTWeights                  c8       5
//   SceneInverseHighLights      c13      1
//   SceneMidTones               c14      1
//   SceneScaledLuminanceWeights c15      1
//   SceneColorize               c16      1
//   GammaColorScaleAndInverse   c17      1
//   GammaOverlayColor           c18      1
//   Texture1                    s0       1
//   Texture2                    s1       1
//   Texture3                    s2       1
//   Texture4                    s3       1
//

    ps_3_0
    def c1, -0.001953125, -0.03125, 16, 0.0625
    def c2, 1.06666672, 0, 9.99999994e-009, 2.20000005
    dcl_texcoord v0.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    add r0.xz, c1.xyyw, v0.xyyw
    mul r1.x, r0.x, c1.z
    frc r0.y, r1.x
    mad r0.w, r0.y, -c1.w, r0.x
    mul r0.xyz, r0.yzww, c8.x
    mul r0.xyz, r0, c2.x
    mov r0.w, c2.y
    texld r1, v0, s0
    mad r0, c9.x, r1, r0
    texld r1, v0, s1
    mad r0, c10.x, r1, r0
    texld r1, v0, s2
    mad r0, c11.x, r1, r0
    texld r1, v0, s3
    mad r0, c12.x, r1, r0
    add_sat r1.xyz, r0, -c0
    mul r1.xyz, r1, c13
    max r2.xyz, r1, c2.z
    log r1.x, r2.x
    log r1.y, r2.y
    log r1.z, r2.z
    mul r1.xyz, r1, c14
    exp_pp r2.x, r1.x
    exp_pp r2.y, r1.y
    exp_pp r2.z, r1.z
    dp3_pp r1.x, r2, c15
    mad_pp r1.xyz, r2, c0.w, r1.x
    mov r2, c17
    mad_pp r1.xyz, r1, r2, c18
    mul_pp r0.xyz, r1, c16
    max r1, c2.z, r0
    log r0.x, r1.x
    log r0.y, r1.y
    log r0.z, r1.z
    log r0.w, r1.w
    mul r1.x, r2.w, c2.w
    mul r0, r0, r1.x
    exp oC0.x, r0.x
    exp oC0.y, r0.y
    exp oC0.z, r0.z
    exp oC0.w, r0.w

// approximately 41 instruction slots used (4 texture, 37 arithmetic)
