//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float4 BloomTintAndScreenBlendThreshold;
//   sampler2D BokehDOFLayerTexture;
//   sampler2D ColorGradingLUT;
//   float4 DOFKernelSize;
//   sampler2D FilterColor1Texture;
//   float4 HalfResMaskRect;
//   sampler2D LowResPostProcessBuffer;
//   float4 MinMaxBlurClamp;
//   float4 MinZ_MaxZRatio;
//   float4 PackedParameters;
//   sampler2D SceneColorTexture;
//   sampler2D SeparateTranslucencyTexture;
//
//
// Registers:
//
//   Name                             Reg   Size
//   -------------------------------- ----- ----
//   PackedParameters                 c0       1
//   MinZ_MaxZRatio                   c2       1
//   MinMaxBlurClamp                  c8       1
//   BloomTintAndScreenBlendThreshold c9       1
//   HalfResMaskRect                  c10      1
//   DOFKernelSize                    c11      1
//   SceneColorTexture                s0       1
//   FilterColor1Texture              s1       1
//   BokehDOFLayerTexture             s2       1
//   SeparateTranslucencyTexture      s3       1
//   ColorGradingLUT                  s4       1
//   LowResPostProcessBuffer          s5       1
//

    ps_3_0
    def c1, 1, 0, 4, 0.5
    def c3, 5, -0.00100000005, 999.999939, 65503
    def c4, 0.300000012, 0.589999974, 0.109999999, -3
    def c5, 9.99999997e-007, 0.454545468, 15, 0.0625
    def c6, 14.9998999, 0.05859375, 0.9375, 0
    def c7, 0.001953125, 0.03125, 0.064453125, 0
    def c12, 0.298999995, 0.587000012, 0.114, 0
    dcl_texcoord v0.zw
    dcl_texcoord1 v1
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s4
    dcl_2d s5
    mov r0.x, c1.x
    add r0.x, r0.x, -c2.y
    mul r1, c1.xxyy, v1.xyxx
    texldl_pp r1, r1, s0
    add r0.x, -r0.x, r1.w
    rcp r0.x, r0.x
    mov r2.x, c0.x
    mad_pp r0.x, -c2.x, r0.x, -r2.x
    mul_sat_pp r0.y, r0_abs.x, c0.y
    cmp_pp r0.x, r0.x, c8.y, c8.x
    pow_pp r1.w, r0.y, c0.z
    min_pp r2.x, r1.w, r0.x
    max_pp r0.x, c0.w, r2.x
    mul_sat r0.x, r0.x, c3.x
    add r0.x, -r0.x, c1.x
    max r0.yz, v1.xzww, c10.xxyw
    min r2.xy, c10.zwzw, r0.yzzw
    texld_pp r3, r2, s5
    mad r0.yzw, r3.xxyz, -c1.z, r1.xxyz
    mul r1.xyz, r3, c1.z
    mad_pp r0.yzw, r3.w, r0, r1.xxyz
    mad r1.xy, r2, c1.wxzw, c1.wyzw
    mul r1.zw, r2.xyxy, c1.xywx
    texld r2, r1.zwzw, s2
    texld r1, r1, s2
    add r3.x, r1.w, c3.y
    rcp r3.y, r1.w
    cmp r3.x, r3.x, r3.y, c3.z
    mad r1.xyz, r1, r3.x, -r0.yzww
    mul_sat r1.w, r1.w, c11.y
    mad r1.xyz, r1.w, r1, r0.yzww
    add r3.xyz, r0.yzww, -r1
    mov r1.w, c1.y
    mov r3.w, c1.x
    mad r1, r0.x, r3, r1
    add r0.x, r2.w, c3.y
    rcp r3.x, r2.w
    cmp r0.x, r0.x, r3.x, c3.z
    mul r3.xyz, r0.x, r2
    mul_sat r0.x, r2.w, c11.y
    mov r3.w, c1.y
    lrp r2, r0.x, r3, r1
    lrp_pp r1.xyz, r2.w, r0.yzww, r2
    min_pp r0.xyz, r1, c3.w
    texld r1, v1, s3
    mad_pp r0.xyz, r0, r1.w, r1
    dp3_pp r0.w, r0, c4
    mul_pp r0.w, r0.w, c4.w
    exp r0.w, r0.w
    mul_sat_pp r0.w, r0.w, c9.w
    texld r1, v0.zwzw, s1
    mul r1.xyz, r1, c9
    mul_pp r1.xyz, r1, c1.z
    mad_pp r0.xyz, r1, r0.w, r0
    max r1.xyz, r0_abs, c5.x
    log r0.x, r1.x
    log r0.y, r1.y
    log r0.z, r1.z
    mul r0.xyz, r0, c5.y
    exp_sat_pp r1.z, r0.x
    exp_sat_pp r1.w, r0.y
    exp_sat_pp r1.xy, r0.z
    mul r0.xyw, r1.xwzz, c6.xzzy
    frc r0.z, r0.x
    add r0.z, -r0.z, r0.x
    mad r0.x, r0.z, c5.w, r0.w
    mad r0.z, r1.y, c5.z, -r0.z
    add r1, r0.xyxy, c7.xyzy
    texld_pp r2, r1, s4
    texld_pp r1, r1.zwzw, s4
    lrp_pp r3.xyz, r0.z, r1, r2
    dp3_pp oC0.w, r3, c12
    mov_pp oC0.xyz, r3

// approximately 76 instruction slots used (9 texture, 67 arithmetic)
