//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float4 BloomTintAndScreenBlendThreshold;
//   sampler2D ColorGradingLUT;
//   sampler2D FilterColor1Texture;
//   float4 HalfResMaskRect;
//   float4 ImageAdjustments1;
//   float4 ImageAdjustments2;
//   float4 ImageAdjustments3;
//   sampler2D LowResPostProcessBuffer;
//   sampler2D NoiseTexture;
//   sampler2D SceneColorTexture;
//
//
// Registers:
//
//   Name                             Reg   Size
//   -------------------------------- ----- ----
//   BloomTintAndScreenBlendThreshold c0       1
//   ImageAdjustments1                c8       1
//   ImageAdjustments2                c9       1
//   ImageAdjustments3                c10      1
//   HalfResMaskRect                  c11      1
//   SceneColorTexture                s0       1
//   FilterColor1Texture              s1       1
//   NoiseTexture                     s2       1
//   ColorGradingLUT                  s3       1
//   LowResPostProcessBuffer          s4       1
//

    ps_3_0
    def c1, 1, 0, 4, 65503
    def c2, 0.300000012, 0.589999974, 0.109999999, -3
    def c3, 10000, 9.99999997e-007, 0.454545468, 0.015625
    def c4, -0.5, 0.00390625, 15, 0.0625
    def c5, 14.9998999, 0.05859375, 0.9375, 0
    def c6, 0.001953125, 0.03125, 0.064453125, 0
    def c7, 0.298999995, 0.587000012, 0.114, 0
    dcl_texcoord v0.zw
    dcl_texcoord1 v1
    dcl_texcoord2 v2.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s4
    mul r0, c1.xxyy, v1.xyxx
    texldl_pp r0, r0, s0
    max r1.xy, v1.zwzw, c11
    min r2.xy, c11.zwzw, r1
    texld_pp r1, r2, s4
    mad r0.xyz, r1, -c1.z, r0
    mul r1.xyz, r1, c1.z
    mad_pp r0.xyz, r1.w, r0, r1
    min_pp r1.xyz, r0, c1.w
    dp3_pp r0.x, r1, c2
    mul_pp r0.x, r0.x, c2.w
    exp r0.x, r0.x
    mul_sat_pp r0.x, r0.x, c0.w
    texld r2, v0.zwzw, s1
    mul r0.yzw, r2.xxyz, c0.xxyz
    mul_pp r0.yzw, r0, c1.z
    mad_pp r0.xyz, r0.yzww, r0.x, r1
    add_pp r1.xyz, r0, c9.x
    rcp r2.z, r1_abs.x
    rcp r2.w, r1_abs.y
    rcp r2.xy, r1_abs.z
    mul_pp r1, r0.zzxy, r2
    mul r2.xyz, r0, c9.w
    add r0, r0.zzxy, -c9.z
    mul_sat_pp r0, r0, c3.x
    max r3.xyz, r2_abs, c3.y
    log r2.x, r3.x
    log r2.y, r3.y
    log r2.z, r3.z
    mul r2.xyz, r2, c3.z
    exp_pp r3.z, r2.x
    exp_pp r3.w, r2.y
    exp_pp r3.xy, r2.z
    mad_pp r2, r1.yyzw, c9.y, -r3.yyzw
    mad_pp r0, r0, r2, r3
    mad_pp r1, r1, c9.y, -r0.yyzw
    mad_sat_pp r0, c10.x, r1, r0
    add_pp r1, -r0.yyzw, c1.x
    mul_pp r1, r1, r1
    mov r2.y, c4.y
    mad r1, r1, c8.w, r2.y
    add r2.xy, c8, v2
    mul r2.xy, r2, c3.w
    texld r2, r2, s2
    add r2.x, r2.x, c4.x
    mad_sat_pp r0, r2.x, r1, r0
    mul r1.xyw, r0.xwzz, c5.xzzy
    frc r0.x, r1.x
    add r0.x, -r0.x, r1.x
    mad r1.x, r0.x, c4.w, r1.w
    mad r0.x, r0.y, c4.z, -r0.x
    add r1, r1.xyxy, c6.xyzy
    texld_pp r2, r1, s3
    texld_pp r1, r1.zwzw, s3
    lrp_pp r3.xyz, r0.x, r1, r2
    dp3_pp oC0.w, r3, c7
    mov_pp oC0.xyz, r3

// approximately 58 instruction slots used (7 texture, 51 arithmetic)
