//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float4 BloomTintAndScreenBlendThreshold;
//   sampler2D ColorGradingLUT;
//   sampler2D FilterColor1Texture;
//   float4 HalfResMaskRect;
//   sampler2D LowResPostProcessBuffer;
//   sampler2D SceneColorTexture;
//   sampler2D SeparateTranslucencyTexture;
//
//
// Registers:
//
//   Name                             Reg   Size
//   -------------------------------- ----- ----
//   BloomTintAndScreenBlendThreshold c0       1
//   HalfResMaskRect                  c8       1
//   SceneColorTexture                s0       1
//   FilterColor1Texture              s1       1
//   SeparateTranslucencyTexture      s2       1
//   ColorGradingLUT                  s3       1
//   LowResPostProcessBuffer          s4       1
//

    ps_3_0
    def c1, 1, 0, 4, 65503
    def c2, 0.300000012, 0.589999974, 0.109999999, -3
    def c3, 9.99999997e-007, 0.454545468, 15, 0.0625
    def c4, 14.9998999, 0.05859375, 0.9375, 0
    def c5, 0.001953125, 0.03125, 0.064453125, 0
    def c6, 0.298999995, 0.587000012, 0.114, 0
    dcl_texcoord v0.zw
    dcl_texcoord1 v1
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s4
    mul r0, c1.xxyy, v1.xyxx
    texldl_pp r0, r0, s0
    max r1.xy, v1.zwzw, c8
    min r2.xy, c8.zwzw, r1
    texld_pp r1, r2, s4
    mad r0.xyz, r1, -c1.z, r0
    mul r1.xyz, r1, c1.z
    mad_pp r0.xyz, r1.w, r0, r1
    min_pp r1.xyz, r0, c1.w
    texld r0, v1, s2
    mad_pp r0.xyz, r1, r0.w, r0
    dp3_pp r0.w, r0, c2
    mul_pp r0.w, r0.w, c2.w
    exp r0.w, r0.w
    mul_sat_pp r0.w, r0.w, c0.w
    texld r1, v0.zwzw, s1
    mul r1.xyz, r1, c0
    mul_pp r1.xyz, r1, c1.z
    mad_pp r0.xyz, r1, r0.w, r0
    max r1.xyz, r0_abs, c3.x
    log r0.x, r1.x
    log r0.y, r1.y
    log r0.z, r1.z
    mul r0.xyz, r0, c3.y
    exp_sat_pp r1.z, r0.x
    exp_sat_pp r1.w, r0.y
    exp_sat_pp r1.xy, r0.z
    mul r0.xyw, r1.xwzz, c4.xzzy
    frc r0.z, r0.x
    add r0.z, -r0.z, r0.x
    mad r0.x, r0.z, c3.w, r0.w
    mad r0.z, r1.y, c3.z, -r0.z
    add r1, r0.xyxy, c5.xyzy
    texld_pp r2, r1, s3
    texld_pp r1, r1.zwzw, s3
    lrp_pp r3.xyz, r0.z, r1, r2
    dp3_pp oC0.w, r3, c6
    mov_pp oC0.xyz, r3

// approximately 39 instruction slots used (7 texture, 32 arithmetic)
