//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float4 SceneCoordinate1ScaleBias;
//   float4 SceneCoordinate2ScaleBias;
//   float4 SceneCoordinate3ScaleBias;
//
//
// Registers:
//
//   Name                      Reg   Size
//   ------------------------- ----- ----
//   SceneCoordinate1ScaleBias c0       1
//   SceneCoordinate2ScaleBias c1       1
//   SceneCoordinate3ScaleBias c2       1
//

    vs_3_0
    dcl_position v0
    dcl_texcoord v1
    dcl_texcoord o0
    dcl_texcoord1 o1
    dcl_texcoord2 o2.xy
    dcl_position o3
    rcp r0.x, v0.w
    mul r0.xy, r0.x, v0
    mad r0.xy, r0, c0, c0.wzzw
    mad o1.zw, r0.xyxy, c1.xyxy, c1.xywz
    mad o0.zw, r0.xyxy, c2.xyxy, c2.xywz
    mov o2.xy, r0
    mov o0.xy, v0
    mov o1.xy, v1
    mov o3, v0

// approximately 9 instruction slots used
