//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float3 ColorScale;
//   float InverseGamma;
//   float4 OverlayColor;
//   sampler2D SceneColorTexture;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   ColorScale        c0       1
//   OverlayColor      c8       1
//   InverseGamma      c9       1
//   SceneColorTexture s0       1
//

    ps_3_0
    def c1, 0.5, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    texld_pp r0, v0, s0
    mul_pp r1.xyz, r0, c0
    mov r2.xyz, c8
    mad_pp r0.xyz, r0, -c0, r2
    mov_pp oC0.w, r0.w
    mad_sat r0.xyz, c8.w, r0, r1
    mul r0.xyz, r0, c9.x
    mov r1.xyz, c0
    mad r1.xyz, r1, c1.x, c1.x
    mul r2.xyz, c8.w, c8
    mad oC0.xyz, r0, r1, r2

// approximately 11 instruction slots used (1 texture, 10 arithmetic)
