//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
    ps_3_0
    def c0, -0.001953125, -0.03125, 16, 0.0625
    def c1, 1.06666672, 0, 0, 0
    dcl_texcoord v0.xy
    add r0.xz, c0.xyyw, v0.xyyw
    mul r1.x, r0.x, c0.z
    frc r0.y, r1.x
    mad r0.w, r0.y, -c0.w, r0.x
    mul oC0.xyz, r0.yzww, c1.x
    mov oC0.w, c1.y

// approximately 6 instruction slots used
