//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float4 BloomTintAndScreenBlendThreshold;
//   sampler2D BokehDOFLayerTexture;
//   sampler2D ColorGradingLUT;
//   float4 DOFKernelSize;
//   sampler2D FilterColor1Texture;
//   float4 HalfResMaskRect;
//   float4 ImageAdjustments2;
//   sampler2D LowResPostProcessBuffer;
//   float4 MinMaxBlurClamp;
//   float4 MinZ_MaxZRatio;
//   float4 PackedParameters;
//   sampler2D SceneColorTexture;
//
//
// Registers:
//
//   Name                             Reg   Size
//   -------------------------------- ----- ----
//   PackedParameters                 c0       1
//   MinZ_MaxZRatio                   c2       1
//   MinMaxBlurClamp                  c8       1
//   BloomTintAndScreenBlendThreshold c9       1
//   ImageAdjustments2                c10      1
//   HalfResMaskRect                  c11      1
//   DOFKernelSize                    c12      1
//   SceneColorTexture                s0       1
//   FilterColor1Texture              s1       1
//   BokehDOFLayerTexture             s2       1
//   ColorGradingLUT                  s3       1
//   LowResPostProcessBuffer          s4       1
//

    ps_3_0
    def c1, 5, -0.00100000005, 999.999939, -65503
    def c3, 1, 0, 4, 0.5
    def c4, 0.300000012, 0.589999974, 0.109999999, -3
    def c5, 14.9998999, 0.05859375, 0.9375, 15
    def c6, 0.0625, 0.001953125, 0.03125, 0.064453125
    def c7, 0.298999995, 0.587000012, 0.114, 0
    dcl_texcoord v0.zw
    dcl_texcoord1 v1
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s4
    mov r0.x, c3.x
    add r0.x, r0.x, -c2.y
    mul r1, c3.xxyy, v1.xyxx
    texldl_pp r1, r1, s0
    add r0.x, -r0.x, r1.w
    rcp r0.x, r0.x
    mov r2.x, c0.x
    mad_pp r0.x, -c2.x, r0.x, -r2.x
    mul_sat_pp r0.y, r0_abs.x, c0.y
    cmp_pp r0.x, r0.x, c8.y, c8.x
    pow_pp r1.w, r0.y, c0.z
    min_pp r2.x, r1.w, r0.x
    max_pp r0.x, c0.w, r2.x
    mul_sat r0.x, r0.x, c1.x
    add r0.x, -r0.x, c3.x
    max r0.yz, v1.xzww, c11.xxyw
    min r2.xy, c11.zwzw, r0.yzzw
    texld_pp r3, r2, s4
    mad r1, r3.zzxy, -c3.z, r1.zzxy
    mul r4, r3.zzxy, c3.z
    mad_pp r1, r3.w, r1, r4
    mad r0.yz, r2.xxyw, c3.xwxw, c3.xwyw
    mul r2.xy, r2, c3.wxzw
    texld r2, r2, s2
    texld r3, r0.yzzw, s2
    add r0.y, r3.w, c1.y
    rcp r0.z, r3.w
    cmp r0.y, r0.y, r0.z, c1.z
    mad r0.yzw, r3.xxyz, r0.y, -r1.xzwy
    mul_sat r3.x, r3.w, c12.y
    mad r3.xyz, r3.x, r0.yzww, r1.zwyw
    add r4.xyz, r1.zwyw, -r3
    mov r3.w, c3.y
    mov r4.w, c3.x
    mad r0, r0.x, r4, r3
    add r3.x, r2.w, c1.y
    rcp r3.y, r2.w
    cmp r3.x, r3.x, r3.y, c1.z
    mul r3.xyz, r2, r3.x
    mul_sat r2.x, r2.w, c12.y
    mov r3.w, c3.y
    lrp r4, r2.x, r3, r0
    lrp_pp r0, r4.w, r1, r4.zzxy
    add r1, r0.yyzw, c1.w
    cmp_pp r0, r1, -c1.w, r0
    dp3_pp r1.x, r0.zwyw, c4
    mul_pp r1.x, r1.x, c4.w
    exp r1.x, r1.x
    mul_sat_pp r1.x, r1.x, c9.w
    texld r2, v0.zwzw, s1
    mul r2, r2.zzxy, c9.zzxy
    mul_pp r2, r2, c3.z
    mad_pp r0, r2, r1.x, r0
    add_pp r1.xyz, r0.zwyw, c10.x
    rcp r2.z, r1_abs.x
    rcp r2.w, r1_abs.y
    rcp r2.xy, r1_abs.z
    mul_pp r0, r0, r2
    mul_sat_pp r0, r0, c10.y
    mul r1.xyw, r0.xwzz, c5.xzzy
    frc r0.x, r1.x
    add r0.x, -r0.x, r1.x
    mad r1.x, r0.x, c6.x, r1.w
    mad r0.x, r0.y, c5.w, -r0.x
    add r1, r1.xyxy, c6.yzwz
    texld_pp r2, r1, s3
    texld_pp r1, r1.zwzw, s3
    lrp_pp r3.xyz, r0.x, r1, r2
    dp3_pp oC0.w, r3, c7
    mov_pp oC0.xyz, r3

// approximately 73 instruction slots used (8 texture, 65 arithmetic)
