//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float4 BloomTintAndScreenBlendThreshold;
//   sampler2D ColorGradingLUT;
//   float4 DOFKernelSize;
//   sampler2D FilterColor1Texture;
//   float4 ImageAdjustments1;
//   float4 MinMaxBlurClamp;
//   float4 MinZ_MaxZRatio;
//   sampler2D NoiseTexture;
//   float4 PackedParameters;
//   sampler2D SceneColorTexture;
//
//
// Registers:
//
//   Name                             Reg   Size
//   -------------------------------- ----- ----
//   PackedParameters                 c0       1
//   MinZ_MaxZRatio                   c2       1
//   MinMaxBlurClamp                  c8       1
//   BloomTintAndScreenBlendThreshold c9       1
//   ImageAdjustments1                c10      1
//   DOFKernelSize                    c11      1
//   SceneColorTexture                s0       1
//   FilterColor1Texture              s1       1
//   NoiseTexture                     s2       1
//   ColorGradingLUT                  s3       1
//

    ps_3_0
    def c1, 1, 0, 14, 0.25999999
    def c3, 0.370000005, 0, 9.99999975e-006, 0.25
    def c4, 4, 0.300000012, 0.589999974, 0.109999999
    def c5, -3, 9.99999997e-007, 0.454545468, 0.015625
    def c6, -0.5, 0.00390625, 15, 0.0625
    def c7, 14.9998999, 0.05859375, 0.9375, 0
    def c12, 0.001953125, 0.03125, 0.064453125, 0
    def c13, 0.298999995, 0.587000012, 0.114, 0
    defi i0, 29, 0, 0, 0
    dcl_texcoord v0.zw
    dcl_texcoord1 v1.xy
    dcl_texcoord2 v2.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    mul r0, c1.xxyy, v1.xyxx
    texldl r0, r0, s0
    mov r0.x, c1.x
    add r0.y, r0.x, -c2.y
    add r0.z, -r0.y, r0.w
    rcp r0.z, r0.z
    max r1.x, c11.x, r0.x
    min r0.x, r1.x, c1.z
    frc r0.w, r0.x
    add r0.x, r0.x, -r0.w
    mov r1.x, c0.x
    mad_pp r0.w, -c2.x, r0.z, -r1.x
    cmp_pp r1.y, r0.w, c8.y, c8.x
    mul_sat_pp r0.w, r0_abs.w, c0.y
    pow_pp r1.z, r0.w, c0.z
    min_pp r0.w, r1.z, r1.y
    max_pp r1.y, c0.w, r0.w
    add r0.w, r0.x, c1.w
    mad_pp r1.y, r1.y, r0.w, c3.x
    mov r2.zw, c1.y
    mov r3.xyz, c1.y
    mov r1.z, c3.z
    mov r4.y, -r0.x
    rep i0
      mov r1.w, r0.x
      break_lt r1.w, r4.y
      mov r5.xyz, r3
      mov r5.w, r1.z
      mov r4.x, -r0.x
      rep i0
        mov r1.w, r0.x
        break_lt r1.w, r4.x
        add r4.zw, r4.xyxy, c3.w
        mad r2.xy, c8.zwzw, r4, v1
        texldl_pp r6, r2, s0
        add r1.w, -r0.y, r6.w
        rcp r1.w, r1.w
        mul_pp r2.x, r1.w, -c2.x
        mad_pp r1.w, -c2.x, r1.w, -r1.x
        cmp_pp r2.y, r1.w, c8.y, c8.x
        mul_sat_pp r1.w, r1_abs.w, c0.y
        pow_pp r3.w, r1.w, c0.z
        min_pp r1.w, r3.w, r2.y
        max_pp r2.y, c0.w, r1.w
        mad_pp r1.w, r2.y, r0.w, c3.x
        add r2.y, -r1.w, r1.y
        mad r2.x, -c2.x, r0.z, -r2.x
        cmp r2.x, r2.x, -c1.y, -c1.x
        cmp r2.x, r2.y, c1.y, r2.x
        cmp_pp r1.w, r2.x, r1.w, r1.y
        dp2add r2.x, r4.zwzw, r4.zwzw, c1.y
        rsq r2.x, r2.x
        rcp r2.x, r2.x
        add r2.x, -r1.w, r2.x
        mov_sat r2.x, -r2.x
        mul r1.w, r1.w, r1.w
        rcp r1.w, r1.w
        mul r1.w, r1.w, r2.x
        mad_pp r6, r6.xyzx, c1.xxxy, c1.yyyx
        mad r5, r6, r1.w, r5
        add r4.x, r4.x, c1.x
      endrep
      mov r3.xyz, r5
      mov r1.z, r5.w
      add r4.y, r4.y, c1.x
    endrep
    rcp r0.x, r1.z
    mul_pp r0.xyz, r0.x, r3
    texld r1, v0.zwzw, s1
    mul r1.xyz, r1, c9
    mul_pp r1.xyz, r1, c4.x
    dp3_pp r0.w, r0, c4.yzww
    mul_pp r0.w, r0.w, c5.x
    exp r0.w, r0.w
    mul_sat_pp r0.w, r0.w, c9.w
    mad_pp r0.xyz, r1, r0.w, r0
    max r1.xyz, r0_abs, c5.y
    log r0.x, r1.x
    log r0.y, r1.y
    log r0.z, r1.z
    mul r0.xyz, r0, c5.z
    exp_sat_pp r1.z, r0.x
    exp_sat_pp r1.w, r0.y
    exp_sat_pp r1.xy, r0.z
    add_pp r0, -r1.yyzw, c1.x
    mul_pp r0, r0, r0
    add r2.xy, c10, v2
    mul r2.xy, r2, c5.w
    texld r2, r2, s2
    add r2.x, r2.x, c6.x
    mov r2.y, c6.y
    mad r0, r0, c10.w, r2.y
    mad_sat_pp r0, r2.x, r0, r1
    mul r1.xyw, r0.xwzz, c7.xzzy
    frc r0.x, r1.x
    add r0.x, -r0.x, r1.x
    mad r0.y, r0.y, c6.z, -r0.x
    mad r1.x, r0.x, c6.w, r1.w
    add r1, r1.xyxy, c12.xyzy
    texld_pp r2, r1, s3
    texld_pp r1, r1.zwzw, s3
    lrp_pp r3.xyz, r0.y, r1, r2
    dp3_pp oC0.w, r3, c13
    mov_pp oC0.xyz, r3

// approximately 121 instruction slots used (8 texture, 113 arithmetic)
