; Inherit the retained generic game defaults.
[Configuration]
BasedOn=..\Engine\Config\BaseGame.ini

[Engine.GameInfo]
DefaultGameType=UDKStarter.UDKStarterGameInfo
DefaultGame=UDKStarter.UDKStarterGameInfo
DefaultServerGame=UDKStarter.UDKStarterGameInfo
MaxPlayers=32

[UTGame.UTAnnouncer]
AnnouncerLevel=2
StatusSoundPackage="UTAnnouncerFemale"
RewardSoundPackage="UTAnnouncerMale"

[UTGame.UTGame]
bWeaponStay=true
BotRatio=+1.0
GoalScore=25
bAutoNumBots=true
bTournament=false
bPlayersMustBeReady=false
NetWait=5
RestartWait=30
MinNetPlayers=1
bWaitForNetPlayers=true
SpawnProtectionTime=+2.0
LateEntryLives=1
TimeLimit=20
bWeaponShouldViewShake=true

[UTGame.UTPlayerController]
bEnableDodging=true
bAlwaysMouseLook=true
bAutoTaunt=false
bLandingShake=true
