//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float4 BloomTintAndScreenBlendThreshold;
//   sampler2D ColorGradingLUT;
//   sampler2D FilterColor1Texture;
//   float4 HalfResMaskRect;
//   float4 ImageAdjustments2;
//   sampler2D LowResPostProcessBuffer;
//   sampler2D SceneColorTexture;
//
//
// Registers:
//
//   Name                             Reg   Size
//   -------------------------------- ----- ----
//   BloomTintAndScreenBlendThreshold c0       1
//   ImageAdjustments2                c8       1
//   HalfResMaskRect                  c9       1
//   SceneColorTexture                s0       1
//   FilterColor1Texture              s1       1
//   ColorGradingLUT                  s2       1
//   LowResPostProcessBuffer          s3       1
//

    ps_3_0
    def c1, 1, 0, 4, -65503
    def c2, 0.300000012, 0.589999974, 0.109999999, -3
    def c3, 14.9998999, 0.05859375, 0.9375, 15
    def c4, 0.0625, 0.001953125, 0.03125, 0.064453125
    def c5, 0.298999995, 0.587000012, 0.114, 0
    dcl_texcoord v0.zw
    dcl_texcoord1 v1
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    mul r0, c1.xxyy, v1.xyxx
    texldl_pp r0, r0, s0
    max r1.xy, v1.zwzw, c9
    min r2.xy, c9.zwzw, r1
    texld_pp r1, r2, s3
    mad r0, r1.zzxy, -c1.z, r0.zzxy
    mul r2, r1.zzxy, c1.z
    mad_pp r0, r1.w, r0, r2
    add r1, r0.yyzw, c1.w
    cmp_pp r0, r1, -c1.w, r0
    dp3_pp r1.x, r0.zwyw, c2
    mul_pp r1.x, r1.x, c2.w
    exp r1.x, r1.x
    mul_sat_pp r1.x, r1.x, c0.w
    texld r2, v0.zwzw, s1
    mul r2, r2.zzxy, c0.zzxy
    mul_pp r2, r2, c1.z
    mad_pp r0, r2, r1.x, r0
    add_pp r1.xyz, r0.zwyw, c8.x
    rcp r2.z, r1_abs.x
    rcp r2.w, r1_abs.y
    rcp r2.xy, r1_abs.z
    mul_pp r0, r0, r2
    mul_sat_pp r0, r0, c8.y
    mul r1.xyw, r0.xwzz, c3.xzzy
    frc r0.x, r1.x
    add r0.x, -r0.x, r1.x
    mad r1.x, r0.x, c4.x, r1.w
    mad r0.x, r0.y, c3.w, -r0.x
    add r1, r1.xyxy, c4.yzwz
    texld_pp r2, r1, s2
    texld_pp r1, r1.zwzw, s2
    lrp_pp r3.xyz, r0.x, r1, r2
    dp3_pp oC0.w, r3, c5
    mov_pp oC0.xyz, r3

// approximately 36 instruction slots used (6 texture, 30 arithmetic)
