/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
    Copyright 1998-2013 Epic Games, Inc. All Rights Reserved.
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#include "UTGameNames.h"

// Split enums from the rest of the header so they can be included earlier
// than the rest of the header file by including this file twice with different
// #define wrappers. See Engine.h and look at EngineClasses.h for an example.
#if !NO_ENUMS && !defined(NAMES_ONLY)

#ifndef INCLUDED_UTGAME_ENUMS
#define INCLUDED_UTGAME_ENUMS 1

enum EBlendDirTypes
{
    FBDir_Forward           =0,
    FBDir_Back              =1,
    FBDir_Left              =2,
    FBDir_Right             =3,
    FBDir_None              =4,
    FBDir_MAX               =5,
};
#define FOREACH_ENUM_EBLENDDIRTYPES(op) \
    op(FBDir_Forward) \
    op(FBDir_Back) \
    op(FBDir_Left) \
    op(FBDir_Right) \
    op(FBDir_None) 
enum EDodgeBlends
{
    DODGEBLEND_None         =0,
    DODGEBLEND_Forward      =1,
    DODGEBLEND_Backward     =2,
    DODGEBLEND_Left         =3,
    DODGEBLEND_Right        =4,
    DODGEBLEND_MAX          =5,
};
#define FOREACH_ENUM_EDODGEBLENDS(op) \
    op(DODGEBLEND_None) \
    op(DODGEBLEND_Forward) \
    op(DODGEBLEND_Backward) \
    op(DODGEBLEND_Left) \
    op(DODGEBLEND_Right) 
enum EBlendFallTypes
{
    FBT_Up                  =0,
    FBT_Down                =1,
    FBT_PreLand             =2,
    FBT_Land                =3,
    FBT_None                =4,
    FBT_MAX                 =5,
};
#define FOREACH_ENUM_EBLENDFALLTYPES(op) \
    op(FBT_Up) \
    op(FBT_Down) \
    op(FBT_PreLand) \
    op(FBT_Land) \
    op(FBT_None) 
enum EWeaponHand
{
    HAND_Hidden             =0,
    HAND_Centered           =1,
    HAND_Left               =2,
    HAND_Right              =3,
    HAND_MAX                =4,
};
#define FOREACH_ENUM_EWEAPONHAND(op) \
    op(HAND_Hidden) \
    op(HAND_Centered) \
    op(HAND_Left) \
    op(HAND_Right) 

#endif // !INCLUDED_UTGAME_ENUMS
#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

#ifndef INCLUDED_UTGAME_CLASSES
#define INCLUDED_UTGAME_CLASSES 1
#define ENABLE_DECLARECLASS_MACRO 1
#include "UnObjBas.h"
#undef ENABLE_DECLARECLASS_MACRO

struct UTAnimBlendBase_eventGetBlendTime_Parms
{
    INT ChildIndex;
    UBOOL bGetDefault;
    FLOAT ReturnValue;
    UTAnimBlendBase_eventGetBlendTime_Parms(EEventParm)
    {
    }
};
class UUTAnimBlendBase : public UAnimNodeBlendList
{
public:
    //## BEGIN PROPS UTAnimBlendBase
    FLOAT BlendTime;
    TArrayNoInit<FLOAT> ChildBlendTimes;
    //## END PROPS UTAnimBlendBase

    FLOAT eventGetBlendTime(INT ChildIndex,UBOOL bGetDefault=FALSE)
    {
        UTAnimBlendBase_eventGetBlendTime_Parms Parms(EC_EventParm);
        Parms.ReturnValue=0;
        Parms.ChildIndex=ChildIndex;
        Parms.bGetDefault=bGetDefault ? FIRST_BITFIELD : FALSE;
        ProcessEvent(FindFunctionChecked(UTGAME_GetBlendTime),&Parms);
        return Parms.ReturnValue;
    }
    DECLARE_CLASS(UUTAnimBlendBase,UAnimNodeBlendList,0,UTGame)
    NO_DEFAULT_CONSTRUCTOR(UUTAnimBlendBase)
};

class UUTAnimBlendByDirection : public UUTAnimBlendBase
{
public:
    //## BEGIN PROPS UTAnimBlendByDirection
    BITFIELD bAdjustRateByVelocity:1;
    SCRIPT_ALIGN;
    BYTE LastDirection;
    SCRIPT_ALIGN;
    //## END PROPS UTAnimBlendByDirection

    DECLARE_CLASS(UUTAnimBlendByDirection,UUTAnimBlendBase,0,UTGame)
	// AnimNode interface
	virtual	void TickAnim( FLOAT DeltaSeconds );
	virtual void OnCeaseRelevant();
	virtual void SetActiveChild( INT ChildIndex, FLOAT BlendTime );
	virtual EBlendDirTypes Get4WayDir();
};

class UUTAnimBlendByDodge : public UUTAnimBlendByDirection
{
public:
    //## BEGIN PROPS UTAnimBlendByDodge
    FName DodgeAnims[16];
    BYTE CurrentDodge;
    SCRIPT_ALIGN;
    //## END PROPS UTAnimBlendByDodge

    DECLARE_CLASS(UUTAnimBlendByDodge,UUTAnimBlendByDirection,0,UTGame)
	virtual	void TickAnim( FLOAT DeltaSeconds );
	virtual void OnCeaseRelevant();
};

class UUTAnimBlendByFall : public UUTAnimBlendBase
{
public:
    //## BEGIN PROPS UTAnimBlendByFall
    BITFIELD bDodgeFall:1;
    SCRIPT_ALIGN;
    BYTE FallState;
    FLOAT LastFallingVelocity;
    //## END PROPS UTAnimBlendByFall

    DECLARE_CLASS(UUTAnimBlendByFall,UUTAnimBlendBase,0,UTGame)
	virtual	void TickAnim( FLOAT DeltaSeconds );
	virtual void SetActiveChild( INT ChildIndex, FLOAT BlendTime );
	virtual void OnChildAnimEnd(UAnimNodeSequence* Child, FLOAT PlayedTime, FLOAT ExcessTime);
	virtual void ChangeFallState(EBlendFallTypes NewState);
};

class UUTAnimBlendByIdle : public UUTAnimBlendBase
{
public:
    //## BEGIN PROPS UTAnimBlendByIdle
    //## END PROPS UTAnimBlendByIdle

    DECLARE_CLASS(UUTAnimBlendByIdle,UUTAnimBlendBase,0,UTGame)
	// AnimNode interface
	virtual	void TickAnim( FLOAT DeltaSeconds );
};

class UUTAnimBlendByPhysics : public UUTAnimBlendBase
{
public:
    //## BEGIN PROPS UTAnimBlendByPhysics
    INT PhysicsMap[12];
    INT LastPhysics;
    //## END PROPS UTAnimBlendByPhysics

    DECLARE_CLASS(UUTAnimBlendByPhysics,UUTAnimBlendBase,0,UTGame)
	virtual	void TickAnim( FLOAT DeltaSeconds );
};

class UUTAnimBlendByPosture : public UUTAnimBlendBase
{
public:
    //## BEGIN PROPS UTAnimBlendByPosture
    //## END PROPS UTAnimBlendByPosture

    DECLARE_CLASS(UUTAnimBlendByPosture,UUTAnimBlendBase,0,UTGame)
	virtual	void TickAnim( FLOAT DeltaSeconds );
};

struct UTAnimBlendByWeapon_eventAnimStopFire_Parms
{
    FLOAT SpecialBlendTime;
    UTAnimBlendByWeapon_eventAnimStopFire_Parms(EEventParm)
    {
    }
};
struct UTAnimBlendByWeapon_eventAnimFire_Parms
{
    FName FireSequence;
    UBOOL bAutoFire;
    FLOAT AnimRate;
    FLOAT SpecialBlendTime;
    UTAnimBlendByWeapon_eventAnimFire_Parms(EEventParm)
    {
    }
};
class UUTAnimBlendByWeapon : public UAnimNodeBlendPerBone
{
public:
    //## BEGIN PROPS UTAnimBlendByWeapon
    BITFIELD bLooping:1;
    FLOAT BlendTime;
    //## END PROPS UTAnimBlendByWeapon

    void eventAnimStopFire(FLOAT SpecialBlendTime=0)
    {
        UTAnimBlendByWeapon_eventAnimStopFire_Parms Parms(EC_EventParm);
        Parms.SpecialBlendTime=SpecialBlendTime;
        ProcessEvent(FindFunctionChecked(UTGAME_AnimStopFire),&Parms);
    }
    void eventAnimFire(FName FireSequence,UBOOL bAutoFire,FLOAT AnimRate=0,FLOAT SpecialBlendTime=0)
    {
        UTAnimBlendByWeapon_eventAnimFire_Parms Parms(EC_EventParm);
        Parms.FireSequence=FireSequence;
        Parms.bAutoFire=bAutoFire ? FIRST_BITFIELD : FALSE;
        Parms.AnimRate=AnimRate;
        Parms.SpecialBlendTime=SpecialBlendTime;
        ProcessEvent(FindFunctionChecked(UTGAME_AnimFire),&Parms);
    }
    DECLARE_CLASS(UUTAnimBlendByWeapon,UAnimNodeBlendPerBone,0,UTGame)
	virtual void OnChildAnimEnd(UAnimNodeSequence* Child, FLOAT PlayedTime, FLOAT ExcessTime);
};

class UUTAnimNodeSequence : public UAnimNodeSequence
{
public:
    //## BEGIN PROPS UTAnimNodeSequence
    BITFIELD bAutoStart:1;
    BITFIELD bResetOnActivate:1;
    SCRIPT_ALIGN;
    //## END PROPS UTAnimNodeSequence

    DECLARE_CLASS(UUTAnimNodeSequence,UAnimNodeSequence,0,UTGame)
	virtual void OnBecomeRelevant();
};

struct UTBot_eventMonitoredPawnAlert_Parms
{
    UTBot_eventMonitoredPawnAlert_Parms(EEventParm)
    {
    }
};
struct UTBot_eventDelayedWarning_Parms
{
    UTBot_eventDelayedWarning_Parms(EEventParm)
    {
    }
};
class AUTBot : public AAIController
{
public:
    //## BEGIN PROPS UTBot
    BITFIELD bHuntPlayer:1;
    BITFIELD bEnemyInfoValid:1;
    FLOAT WarningDelay;
    class AProjectile* WarningProjectile;
    FVector MonitorStartLoc;
    class APawn* MonitoredPawn;
    FLOAT MonitorMaxDistSq;
    FVector LastSeenPos;
    FVector LastSeeingPos;
    FLOAT LastSeenTime;
    //## END PROPS UTBot

    DECLARE_FUNCTION(execWaitToSeeEnemy);
    DECLARE_FUNCTION(execCanMakePathTo);
    void eventMonitoredPawnAlert()
    {
        ProcessEvent(FindFunctionChecked(UTGAME_MonitoredPawnAlert),NULL);
    }
    void eventDelayedWarning()
    {
        ProcessEvent(FindFunctionChecked(UTGAME_DelayedWarning),NULL);
    }
    DECLARE_CLASS(AUTBot,AAIController,0,UTGame)
	DECLARE_FUNCTION(execPollWaitToSeeEnemy);
	UBOOL Tick( FLOAT DeltaSeconds, ELevelTick TickType );
	virtual void UpdateEnemyInfo(APawn* AcquiredEnemy);
};

class UUTCheatManager : public UCheatManager
{
public:
    //## BEGIN PROPS UTCheatManager
    //## END PROPS UTCheatManager

    DECLARE_CLASS(UUTCheatManager,UCheatManager,0,UTGame)
    NO_DEFAULT_CONSTRUCTOR(UUTCheatManager)
};

class AUTPawn : public APawn
{
public:
    //## BEGIN PROPS UTPawn
    BITFIELD bNoTeamBeacon:1;
    BITFIELD bBehindView:1;
    BITFIELD bFixedView:1;
    BITFIELD bCanDoubleJump:1;
    SCRIPT_ALIGN;
    FVector FixedViewLoc;
    FRotator FixedViewRot;
    TArrayNoInit<class UClass*> DefaultInventory;
    INT spree;
    FLOAT DodgeSpeed;
    FLOAT DodgeSpeedZ;
    BYTE CurrentDir;
    BYTE WeaponHand;
    INT MultiJumpRemaining;
    INT MaxMultiJump;
    INT MultiJumpBoost;
    INT SuperHealthMax;
    FLOAT ShieldStrength;
    class UClass* SoundGroupClass;
    class UClass* CurrentWeaponAttachmentClass;
    class AUTWeaponAttachment* CurrentWeaponAttachment;
    FName WeaponBone;
    //## END PROPS UTPawn

    DECLARE_ABSTRACT_CLASS(AUTPawn,APawn,0|CLASS_Config,UTGame)
	virtual UBOOL TryJumpUp(FVector Dir, FVector Destination, DWORD TraceFlags, UBOOL bNoVisibility);
};

#undef DECLARE_CLASS
#undef DECLARE_CASTED_CLASS
#undef DECLARE_ABSTRACT_CLASS
#undef DECLARE_ABSTRACT_CASTED_CLASS
#endif // !INCLUDED_UTGAME_CLASSES
#endif // !NAMES_ONLY

AUTOGENERATE_FUNCTION(AUTBot,-1,execCanMakePathTo);
AUTOGENERATE_FUNCTION(AUTBot,-1,execWaitToSeeEnemy);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef UTGAME_NATIVE_DEFS
#define UTGAME_NATIVE_DEFS

#define AUTO_INITIALIZE_REGISTRANTS_UTGAME \
	UUTAnimBlendBase::StaticClass(); \
	UUTAnimBlendByDirection::StaticClass(); \
	UUTAnimBlendByDodge::StaticClass(); \
	UUTAnimBlendByFall::StaticClass(); \
	UUTAnimBlendByIdle::StaticClass(); \
	UUTAnimBlendByPhysics::StaticClass(); \
	UUTAnimBlendByPosture::StaticClass(); \
	UUTAnimBlendByWeapon::StaticClass(); \
	UUTAnimNodeSequence::StaticClass(); \
	AUTBot::StaticClass(); \
	GNativeLookupFuncs.Set(FName("UTBot"), GUTGameAUTBotNatives); \
	UUTCheatManager::StaticClass(); \
	AUTPawn::StaticClass(); \

#endif // UTGAME_NATIVE_DEFS

#ifdef NATIVES_ONLY
FNativeFunctionLookup GUTGameAUTBotNatives[] = 
{ 
	MAP_NATIVE(AUTBot, execCanMakePathTo)
	MAP_NATIVE(AUTBot, execWaitToSeeEnemy)
	{NULL, NULL}
};

#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_OFFSET_NODIE(UUTAnimBlendBase,UTAnimBlendBase,BlendTime)
VERIFY_CLASS_OFFSET_NODIE(UUTAnimBlendBase,UTAnimBlendBase,ChildBlendTimes)
VERIFY_CLASS_SIZE_NODIE(UUTAnimBlendBase)
VERIFY_CLASS_OFFSET_NODIE(UUTAnimBlendByDirection,UTAnimBlendByDirection,LastDirection)
VERIFY_CLASS_SIZE_NODIE(UUTAnimBlendByDirection)
VERIFY_CLASS_OFFSET_NODIE(UUTAnimBlendByDodge,UTAnimBlendByDodge,DodgeAnims)
VERIFY_CLASS_OFFSET_NODIE(UUTAnimBlendByDodge,UTAnimBlendByDodge,CurrentDodge)
VERIFY_CLASS_SIZE_NODIE(UUTAnimBlendByDodge)
VERIFY_CLASS_OFFSET_NODIE(UUTAnimBlendByFall,UTAnimBlendByFall,FallState)
VERIFY_CLASS_OFFSET_NODIE(UUTAnimBlendByFall,UTAnimBlendByFall,LastFallingVelocity)
VERIFY_CLASS_SIZE_NODIE(UUTAnimBlendByFall)
VERIFY_CLASS_SIZE_NODIE(UUTAnimBlendByIdle)
VERIFY_CLASS_OFFSET_NODIE(UUTAnimBlendByPhysics,UTAnimBlendByPhysics,PhysicsMap)
VERIFY_CLASS_OFFSET_NODIE(UUTAnimBlendByPhysics,UTAnimBlendByPhysics,LastPhysics)
VERIFY_CLASS_SIZE_NODIE(UUTAnimBlendByPhysics)
VERIFY_CLASS_SIZE_NODIE(UUTAnimBlendByPosture)
VERIFY_CLASS_OFFSET_NODIE(UUTAnimBlendByWeapon,UTAnimBlendByWeapon,BlendTime)
VERIFY_CLASS_SIZE_NODIE(UUTAnimBlendByWeapon)
VERIFY_CLASS_SIZE_NODIE(UUTAnimNodeSequence)
VERIFY_CLASS_OFFSET_NODIE(AUTBot,UTBot,WarningDelay)
VERIFY_CLASS_OFFSET_NODIE(AUTBot,UTBot,LastSeenTime)
VERIFY_CLASS_SIZE_NODIE(AUTBot)
VERIFY_CLASS_SIZE_NODIE(UUTCheatManager)
VERIFY_CLASS_OFFSET_NODIE(AUTPawn,UTPawn,FixedViewLoc)
VERIFY_CLASS_OFFSET_NODIE(AUTPawn,UTPawn,WeaponBone)
VERIFY_CLASS_SIZE_NODIE(AUTPawn)
#endif // VERIFY_CLASS_SIZES
#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
