//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float4 BloomTintAndScreenBlendThreshold;
//   sampler2D ColorGradingLUT;
//   sampler2D FilterColor1Texture;
//   float4 HalfResMaskRect;
//   float4 ImageAdjustments2;
//   float4 ImageAdjustments3;
//   sampler2D LowResPostProcessBuffer;
//   sampler2D SceneColorTexture;
//   sampler2D SeparateTranslucencyTexture;
//
//
// Registers:
//
//   Name                             Reg   Size
//   -------------------------------- ----- ----
//   BloomTintAndScreenBlendThreshold c0       1
//   ImageAdjustments2                c8       1
//   ImageAdjustments3                c9       1
//   HalfResMaskRect                  c10      1
//   SceneColorTexture                s0       1
//   FilterColor1Texture              s1       1
//   SeparateTranslucencyTexture      s2       1
//   ColorGradingLUT                  s3       1
//   LowResPostProcessBuffer          s4       1
//

    ps_3_0
    def c1, 1, 0, 4, 65503
    def c2, 0.300000012, 0.589999974, 0.109999999, -3
    def c3, 10000, 9.99999997e-007, 0.454545468, 15
    def c4, 14.9998999, 0.05859375, 0.9375, 0.0625
    def c5, 0.001953125, 0.03125, 0.064453125, 0
    def c6, 0.298999995, 0.587000012, 0.114, 0
    dcl_texcoord v0.zw
    dcl_texcoord1 v1
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s4
    mul r0, c1.xxyy, v1.xyxx
    texldl_pp r0, r0, s0
    max r1.xy, v1.zwzw, c10
    min r2.xy, c10.zwzw, r1
    texld_pp r1, r2, s4
    mad r0.xyz, r1, -c1.z, r0
    mul r1.xyz, r1, c1.z
    mad_pp r0.xyz, r1.w, r0, r1
    min_pp r1.xyz, r0, c1.w
    texld r0, v1, s2
    mad_pp r0.xyz, r1, r0.w, r0
    dp3_pp r0.w, r0, c2
    mul_pp r0.w, r0.w, c2.w
    exp r0.w, r0.w
    mul_sat_pp r0.w, r0.w, c0.w
    texld r1, v0.zwzw, s1
    mul r1.xyz, r1, c0
    mul_pp r1.xyz, r1, c1.z
    mad_pp r0.xyz, r1, r0.w, r0
    add_pp r1.xyz, r0, c8.x
    rcp r2.z, r1_abs.x
    rcp r2.w, r1_abs.y
    rcp r2.xy, r1_abs.z
    mul_pp r1, r0.zzxy, r2
    mul r2.xyz, r0, c8.w
    add r0, r0.zzxy, -c8.z
    mul_sat_pp r0, r0, c3.x
    max r3.xyz, r2_abs, c3.y
    log r2.x, r3.x
    log r2.y, r3.y
    log r2.z, r3.z
    mul r2.xyz, r2, c3.z
    exp_pp r3.z, r2.x
    exp_pp r3.w, r2.y
    exp_pp r3.xy, r2.z
    mad_pp r2, r1.yyzw, c8.y, -r3.yyzw
    mad_pp r0, r0, r2, r3
    mad_pp r1, r1, c8.y, -r0.yyzw
    mad_sat_pp r0, c9.x, r1, r0
    mul r1.xyw, r0.xwzz, c4.xzzy
    frc r0.x, r1.x
    add r0.x, -r0.x, r1.x
    mad r1.x, r0.x, c4.w, r1.w
    mad r0.x, r0.y, c3.w, -r0.x
    add r1, r1.xyxy, c5.xyzy
    texld_pp r2, r1, s3
    texld_pp r1, r1.zwzw, s3
    lrp_pp r3.xyz, r0.x, r1, r2
    dp3_pp oC0.w, r3, c6
    mov_pp oC0.xyz, r3

// approximately 51 instruction slots used (7 texture, 44 arithmetic)
