//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float4 BloomTintAndScreenBlendThreshold;
//   sampler2D BokehDOFLayerTexture;
//   sampler2D ColorGradingLUT;
//   float4 DOFKernelSize;
//   sampler2D FilterColor1Texture;
//   float4 HalfResMaskRect;
//   float4 ImageAdjustments2;
//   float4 ImageAdjustments3;
//   sampler2D LowResPostProcessBuffer;
//   float4 MinMaxBlurClamp;
//   float4 MinZ_MaxZRatio;
//   float4 PackedParameters;
//   sampler2D SceneColorTexture;
//
//
// Registers:
//
//   Name                             Reg   Size
//   -------------------------------- ----- ----
//   PackedParameters                 c0       1
//   MinZ_MaxZRatio                   c2       1
//   MinMaxBlurClamp                  c8       1
//   BloomTintAndScreenBlendThreshold c9       1
//   ImageAdjustments2                c10      1
//   ImageAdjustments3                c11      1
//   HalfResMaskRect                  c12      1
//   DOFKernelSize                    c13      1
//   SceneColorTexture                s0       1
//   FilterColor1Texture              s1       1
//   BokehDOFLayerTexture             s2       1
//   ColorGradingLUT                  s3       1
//   LowResPostProcessBuffer          s4       1
//

    ps_3_0
    def c1, 1, 0, 4, 0.5
    def c3, 5, -0.00100000005, 999.999939, 65503
    def c4, 0.300000012, 0.589999974, 0.109999999, -3
    def c5, 10000, 9.99999997e-007, 0.454545468, 15
    def c6, 14.9998999, 0.05859375, 0.9375, 0.0625
    def c7, 0.001953125, 0.03125, 0.064453125, 0
    def c14, 0.298999995, 0.587000012, 0.114, 0
    dcl_texcoord v0.zw
    dcl_texcoord1 v1
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s4
    mov r0.x, c1.x
    add r0.x, r0.x, -c2.y
    mul r1, c1.xxyy, v1.xyxx
    texldl_pp r1, r1, s0
    add r0.x, -r0.x, r1.w
    rcp r0.x, r0.x
    mov r2.x, c0.x
    mad_pp r0.x, -c2.x, r0.x, -r2.x
    mul_sat_pp r0.y, r0_abs.x, c0.y
    cmp_pp r0.x, r0.x, c8.y, c8.x
    pow_pp r1.w, r0.y, c0.z
    min_pp r2.x, r1.w, r0.x
    max_pp r0.x, c0.w, r2.x
    mul_sat r0.x, r0.x, c3.x
    add r0.x, -r0.x, c1.x
    max r0.yz, v1.xzww, c12.xxyw
    min r2.xy, c12.zwzw, r0.yzzw
    texld_pp r3, r2, s4
    mad r0.yzw, r3.xxyz, -c1.z, r1.xxyz
    mul r1.xyz, r3, c1.z
    mad_pp r0.yzw, r3.w, r0, r1.xxyz
    mad r1.xy, r2, c1.wxzw, c1.wyzw
    mul r1.zw, r2.xyxy, c1.xywx
    texld r2, r1.zwzw, s2
    texld r1, r1, s2
    add r3.x, r1.w, c3.y
    rcp r3.y, r1.w
    cmp r3.x, r3.x, r3.y, c3.z
    mad r1.xyz, r1, r3.x, -r0.yzww
    mul_sat r1.w, r1.w, c13.y
    mad r1.xyz, r1.w, r1, r0.yzww
    add r3.xyz, r0.yzww, -r1
    mov r1.w, c1.y
    mov r3.w, c1.x
    mad r1, r0.x, r3, r1
    add r0.x, r2.w, c3.y
    rcp r3.x, r2.w
    cmp r0.x, r0.x, r3.x, c3.z
    mul r3.xyz, r0.x, r2
    mul_sat r0.x, r2.w, c13.y
    mov r3.w, c1.y
    lrp r2, r0.x, r3, r1
    lrp_pp r1.xyz, r2.w, r0.yzww, r2
    min_pp r0.xyz, r1, c3.w
    dp3_pp r0.w, r0, c4
    mul_pp r0.w, r0.w, c4.w
    exp r0.w, r0.w
    mul_sat_pp r0.w, r0.w, c9.w
    texld r1, v0.zwzw, s1
    mul r1.xyz, r1, c9
    mul_pp r1.xyz, r1, c1.z
    mad_pp r0.xyz, r1, r0.w, r0
    add r1, r0.zzxy, -c10.z
    mul_sat_pp r1, r1, c5.x
    add_pp r2.xyz, r0, c10.x
    rcp r3.z, r2_abs.x
    rcp r3.w, r2_abs.y
    rcp r3.xy, r2_abs.z
    mul_pp r2, r0.zzxy, r3
    mul r0.xyz, r0, c10.w
    max r3.xyz, r0_abs, c5.y
    log r0.x, r3.x
    log r0.y, r3.y
    log r0.z, r3.z
    mul r0.xyz, r0, c5.z
    exp_pp r3.z, r0.x
    exp_pp r3.w, r0.y
    exp_pp r3.xy, r0.z
    mad_pp r0, r2.yyzw, c10.y, -r3.yyzw
    mad_pp r0, r1, r0, r3
    mad_pp r1, r2, c10.y, -r0.yyzw
    mad_sat_pp r0, c11.x, r1, r0
    mul r1.xyw, r0.xwzz, c6.xzzy
    frc r0.x, r1.x
    add r0.x, -r0.x, r1.x
    mad r1.x, r0.x, c6.w, r1.w
    mad r0.x, r0.y, c5.w, -r0.x
    add r1, r1.xyxy, c7.xyzy
    texld_pp r2, r1, s3
    texld_pp r1, r1.zwzw, s3
    lrp_pp r3.xyz, r0.x, r1, r2
    dp3_pp oC0.w, r3, c14
    mov_pp oC0.xyz, r3

// approximately 86 instruction slots used (8 texture, 78 arithmetic)
