//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
    vs_3_0
    def c0, 1, 0, 0, 0
    dcl_position v0
    dcl_texcoord v1
    dcl_texcoord o0.xy
    dcl_position o1
    mov o0.xy, v1
    mad o1, v0.xyxx, c0.xxyy, c0.yyyx

// approximately 2 instruction slots used
